<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.mohakchavan</groupId>
    <artifactId>general-utils</artifactId>
    <version>${revision}${changelist}</version>
    <packaging>jar</packaging>

    <name>general-utils</name>
    <url>https://github.com/mohakchavan/general-utils</url>
    <developers>
        <developer>
            <name>Mohak Chavan</name>
            <id>mohakchavan</id>
        </developer>
    </developers>

    <!--<distributionManagement>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/mohakchavan/general-utils</url>
        </repository>
    </distributionManagement>-->

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>21</maven.compiler.release>

        <revision>0.0.1</revision>
        <changelist>-SNAPSHOT</changelist>

        <profile.suffix/> <!-- This property is intentionally kept empty. -->
        <custom.finalName>${project.artifactId}-${project.version}${profile.suffix}</custom.finalName>

        <lazysodium.version>5.2.0</lazysodium.version>
        <logback.version>1.5.32</logback.version>
    </properties>

    <profiles>

        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <activeProfile>dev</activeProfile>
                <logging.defaultLogLevel>trace</logging.defaultLogLevel>
                <logging.fileLogging.enabled>false</logging.fileLogging.enabled>
                <profile.suffix>-${activeProfile}</profile.suffix>
            </properties>
        </profile>

        <profile>
            <id>prod</id>
            <properties>
                <activeProfile>prod</activeProfile>
                <logging.defaultLogLevel>debug</logging.defaultLogLevel>
                <logging.fileLogging.enabled>true</logging.fileLogging.enabled>
                <logging.fileLogging.file>./${project.name}-logs.txt</logging.fileLogging.file>
                <profile.suffix>-${activeProfile}</profile.suffix>
            </properties>
            <build>
                <plugins>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <showWarnings>true</showWarnings>
                            <compilerArgs>
                                <arg>-Xlint:all</arg>
                                <arg>-Werror</arg>
                            </compilerArgs>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <failOnWarnings>true</failOnWarnings>
                        </configuration>
                    </plugin>

                </plugins>
            </build>
        </profile>

        <profile>
            <id>release</id>
            <properties>
                <activeProfile>release</activeProfile>
                <logging.defaultLogLevel>debug</logging.defaultLogLevel>
                <logging.fileLogging.enabled>true</logging.fileLogging.enabled>
                <logging.fileLogging.file>./${project.name}-logs.txt</logging.fileLogging.file>
                <!--<profile.suffix>-${activeProfile}</profile.suffix>-->
                <profile.suffix/>
            </properties>
            <build>
                <plugins>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <signer>gpg</signer>
                                    <bestPractices>true</bestPractices>
                                    <ascDirectory>${project.build.directory}</ascDirectory>
                                    <keyname>${env.SIGNING_GPG_KEY_ID}</keyname>
                                    <passphraseEnvName>SIGNING_GPG_KEY_PASS</passphraseEnvName>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jarsigner-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <archive>
                                        ${project.build.directory}/${custom.finalName}-shaded.jar
                                    </archive>
                                    <arguments>
                                        <argument>-signedjar</argument>
                                        <argument>${project.build.directory}/${custom.finalName}-shaded.jar
                                        </argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>verify</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <archive>${project.build.directory}/${custom.finalName}-shaded.jar</archive>
                                </configuration>
                            </execution>
                        </executions>
                        <configuration>
                            <keystore>${env.KEYSTORE_FILE}</keystore>
                            <alias>${env.KEYSTORE_ALIAS}</alias>
                            <storepass>${env.KEYSTORE_STORE_PASS}</storepass>
                            <keypass>${env.KEYSTORE_KEY_PASS}</keypass>
                            <removeExistingSignatures>true</removeExistingSignatures>
                        </configuration>
                    </plugin>

                </plugins>
            </build>
        </profile>
    </profiles>

    <dependencies>

        <!--<editor-fold desc="Dependencies">-->
        <!-- Source: https://mvnrepository.com/artifact/com.goterl/lazysodium-java -->
        <dependency>
            <groupId>com.goterl</groupId>
            <artifactId>lazysodium-java</artifactId>
            <version>${lazysodium.version}</version>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/ch.qos.logback/logback-classic -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <!--</editor-fold>-->

        <!--<editor-fold desc="Test Dependencies">-->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <!--</editor-fold>-->
    </dependencies>

    <build>

        <finalName>${custom.finalName}</finalName>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>*.properties</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>*.properties</exclude>
                </excludes>
            </resource>
        </resources>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <propertiesEncoding>${project.build.sourceEncoding}</propertiesEncoding>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>io.github.mohakchavan.GeneralUtils</mainClass>
                                </transformer>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>module-info.class</exclude>
                                        <exclude>META-INF/*.MF</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <!--<minimizeJar>true</minimizeJar>--> <!-- DO NOT MINIMIZE. -->
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <finalName>${custom.finalName}-shaded</finalName>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>s</shadedClassifierName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-clean-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.15.0</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-deploy-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.1.4</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-install-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>3.1.4</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-resources-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-site-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.21.0</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.5</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-source-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.4.0</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-javadoc-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.12.0</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-shade-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.6.2</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-gpg-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-gpg-plugin</artifactId>
                    <version>3.2.8</version>
                </plugin>
                <plugin>
                    <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jarsigner-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jarsigner-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
            </plugins>
        </pluginManagement>

    </build>

</project>
