application.name=@name@
application.version=@version@

# Configure Active Profile
profiles.active=@activeProfile@

customLogging.defaultLogLevel=@logging.defaultLogLevel@
customLogging.fileLogging.enabled=@logging.fileLogging.enabled@
customLogging.fileLogging.file=@logging.fileLogging.file@
customLogging.dateTimeFormat=yyyy-MM-dd'T'HH:mm:ss.SSSZ,UTC