application.name=@name@
application.version=@version@

# Configure Active Profile
profiles.active=@activeProfile@

customLogging.defaultLogLevel=${logging.defaultLogLevel}
customLogging.fileLogging.enabled=@logging.fileLogging.enabled@
customLogging.fileLogging.file=@logging.fileLogging.file@
customLogging.dateTimeFormat=@custom.dateTimeFormat@,UTC