name: Delete Caches

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "development_cache"


jobs:

  delete-cache:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:

      - name: Set run mode
        id: set-run-mode
        shell: sh
        run: |
          echo "Ref: ${{github.ref}}"
          if [ "${{github.event_name}}" = "workflow_dispatch" ]; then
            echo "Workflow is run manually."
            echo "branch=${{github.event.ref}}" >> $GITHUB_OUTPUT

          elif [ "${{github.event_name}}" = "pull_request" ]; then
            echo "Workflow is run on pull request event."
            echo "branch=${{github.event.pull_request.head.ref}}" >> $GITHUB_OUTPUT

          fi

      - name: Clean-up
        shell: sh
        run: |
          echo "Acquiring caches"
          echo "Branch: ${{steps.set-run-mode.outputs.branch}}"
