name: Generate JAR on Release

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  build-jar-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"

      - name: Build
        shell: sh
        run: |
          chmod +x mvnw
          ./mvnw clean package --activate-profiles !dev,prod

  build-jar-release:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: release
      deployment: false
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"
          gpg-private-key: ${{secrets.SIGNING_GPG_KEY}}

      - name: Decode Keystore
        if: ${{ steps.set-run-mode.outputs.run-mode == 2 }}
        shell: sh
        run: |
          echo "${{secrets.KEYSTORE_FILE}}" | base64 --decode --ignore-garbage > general-utils-keystore.p12

      - name: Build Release
        if: ${{ steps.set-run-mode.outputs.run-mode == 2 }}
        shell: sh
        env:
          KEYSTORE_FILE: general-utils-keystore.p12
          KEYSTORE_ALIAS: ${{secrets.KEYSTORE_ALIAS}}
          KEYSTORE_STORE_PASS: ${{secrets.KEYSTORE_STORE_PASS}}
          KEYSTORE_KEY_PASS: ${{secrets.KEYSTORE_KEY_PASS}}
          SIGNING_GPG_KEY_ID: ${{vars.SIGNING_GPG_KEY_ID}}
          SIGNING_GPG_KEY_PASS: ${{secrets.SIGNING_GPG_KEY_PASS}}
        run: |
          chmod +x mvnw
          ./mvnw clean verify --activate-profiles !dev,prod,release

      - name: Checksums
        shell: sh
        run: |
          sh .github/scripts/create-checksum.sh
          ls -als target

      - name: Upload Release Assets
        run: |
          echo "Release Action: ${{github.event.action}}"
          echo "Release ID: ${{github.event.release.id}}"
          
          echo "=======Calling Release Info======="
          curl --location --request GET "https://api.github.com/repos/${{github.repository}}/releases/${{github.event.release.id}}"\
            --verbose --output resp.txt
          
          cleanUrl=$(jq -r ".upload_url" resp.txt | { read url; echo "${url%\{*}"; })
          echo "=======Uploading JAR Asset======="
          for file in ./target/*.jar ./target/*.pom ./target/*.md5 ./target/*.sha*; do
            echo
            echo "=======Uploading $file file======="
            curl --location --request POST --header "Authorization: Bearer ${{github.token}}" \
              --header "Content-Type: application/java-archive" "$cleanUrl?name=${file##*/}" \
                --data-binary "@$file" --verbose
          done
            
