name: Generate JAR on Release

on:
  workflow_dispatch:
  release:
    types:
      - edited
      - published

jobs:

  build-jar:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"

      - name: Build
        if: false
        run: |
          chmod +x mvnw
          ./mvnw clean package -P prod

      - name: Upload
        run: |
          echo "Event Name"
          echo "${{github.event_name}}"
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            echo "Workflow is run manually. No need to upload release assests."
          elif [[ "${{github.event_name}}" == "release" ]]; then
            echo "Workflow run on release event. Upload to release assets."
            echo "Release Action: ${{github.event.action}}"
            echo "Release ID: ${{github.event.release.id}}"
            echo "Release Assets URL: ${{github.event.release.assets_url}}"
            
            curl --location "https://api.github.com/repos/${{github.repository}}/releases/${{github.event.release.id}}"\
              --verbose --output resp.txt
            cat resp.txt
            
          fi
          
