name: Test Code

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "development_automate"

jobs:

  test-code:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check if branch updated
        run: |
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            echo "Workflow is run manually. No need to check if branch is updated or not."
          
          elif [[ "${{github.event_name}}" == "pull_request" ]]; then
            echo "Workflow is run on pull request event. Need to check if branch is updated or not."
            echo "Head SHA: ${{github.event.pull_request.head.sha}}"
            echo "Base SHA: ${{github.event.pull_request.base.sha}}"
          
            if ( git merge-base --is-ancestor ${{github.event.pull_request.head.sha}} ${{github.event.pull_request.base.sha}} ); then
              echo "Branch is updated."
          
            else
              echo "Branch is not updated."
              exit 1
          
            fi
          
          fi

      - name: Setup Java
        uses: actions/setup-java@v5
        if: false
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"

      - name: Clean, Complie & Test Code
        if: false
        run: |
          chmod +x mvnw
          ./mvnw clean test --activate-profiles release,!dev
