name: Test Code

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "development_automate"


jobs:

  test-code:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Check if branch updated
        shell: sh
        run: |
          if [ "${{github.event_name}}" = "workflow_dispatch" ]; then
            echo "Workflow is run manually. No need to check if branch is updated or not."
          
          elif [ "${{github.event_name}}" = "pull_request" ]; then
            echo "Workflow is run on pull request event. Need to check if branch is updated or not."
            echo "Base(Target) Ref: ${{github.event.pull_request.base.ref}}"
            echo "Base(Target) SHA: ${{github.event.pull_request.base.sha}}"
            echo "Head(Source) Ref: ${{github.event.pull_request.head.ref}}"
            echo "Head(Source) SHA: ${{github.event.pull_request.head.sha}}"
            
            echo "Branch all"
            git branch --all
          
            if ( git merge-base --is-ancestor "${{github.event.pull_request.base.sha}}" "${{github.event.pull_request.head.sha}}" &&
                  git merge-base --is-ancestor "origin/${{github.event.pull_request.base.ref}}" "origin/${{github.event.pull_request.head.ref}}" ); then
              echo "Head(Source) branch is updated."
          
            else
              echo "Head(Source) branch is not updated."
              exit 1
          
            fi
          
          fi

      - name: Setup Java
        uses: actions/setup-java@v5
        if: false
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"

      - name: Clean, Complie & Test Code
        if: false
        run: |
          chmod +x mvnw
          ./mvnw clean test --activate-profiles release,!dev
