# This workflow file is used only for testing of workflows.
#
# DO NOT SUBMIT CHANGES FOR THIS FILE.
name: Test Deploy

on:
  workflow_dispatch:

jobs:

  test-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            pom.xml
            mvnw
            .mvn

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"

      - name: Show Settings
        shell: sh
        run: |
          echo "${{secrets.KEYSTORE_FILE}}" | base64 --decode --ignore-garbage > general-utils-keystore.p12
          ls -als
          ls -als ./.mvn/wrapper

      - name: Build
        env:
          KEYSTORE_FILE: general-utils-keystore.p12
          KEYSTORE_ALIAS: ${{secrets.KEYSTORE_ALIAS}}
          KEYSTORE_STORE_PASS: ${{secrets.KEYSTORE_STORE_PASS}}
          KEYSTORE_KEY_PASS: ${{secrets.KEYSTORE_KEY_PASS}}
        shell: sh
        run: |
          cat ~/.m2/settings.xml
          chmod +x mvnw
          ./mvnw clean validate dependency:resolve
          

