name: Compile & Test Code

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "development"

jobs:

  test-code:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Set run mode
        id: set-run-mode
        shell: sh
        run: |
          if [ "${{github.event_name}}" = "workflow_dispatch" ]; then
            echo "Workflow is run manually."
            echo "run-mode=1" >> $GITHUB_OUTPUT
          
          elif [ "${{github.event_name}}" = "pull_request" ]; then
            echo "Workflow is run on pull request event."
            echo "run-mode=2" >> $GITHUB_OUTPUT
          
          fi

      - name: Fetch base & head branches
        if: ${{ steps.set-run-mode.outputs.run-mode == 2 }}
        shell: sh
        run: |
          echo "Fetch base ref"
          git fetch --no-tags origin ${{github.event.pull_request.base.ref}}:${{github.event.pull_request.base.ref}}
          git branch --set-upstream-to origin/${{github.event.pull_request.base.ref}} ${{github.event.pull_request.base.ref}}
          echo "Fetch head ref"
          git fetch --no-tags origin ${{github.event.pull_request.head.ref}}:${{github.event.pull_request.head.ref}}
          git branch --set-upstream-to origin/${{github.event.pull_request.head.ref}} ${{github.event.pull_request.head.ref}}
          echo "Branch all"
          git branch --all

      - name: Check if branch updated
        if: ${{ steps.set-run-mode.outputs.run-mode == 2 }}
        shell: sh
        run: |
          echo "Workflow is run on pull request event. Need to check if branch is updated or not."
          echo "Base(Target) Ref: ${{github.event.pull_request.base.ref}}"
          echo "Base(Target) SHA: ${{github.event.pull_request.base.sha}}"
          echo "Head(Source) Ref: ${{github.event.pull_request.head.ref}}"
          echo "Head(Source) SHA: ${{github.event.pull_request.head.sha}}"
          
          if ( git merge-base --is-ancestor "${{github.event.pull_request.base.sha}}" "${{github.event.pull_request.head.sha}}" &&
                git merge-base --is-ancestor "origin/${{github.event.pull_request.base.ref}}" "origin/${{github.event.pull_request.head.ref}}" ); then
            echo "Head(Source) branch is updated."
          
          else
            echo "Head(Source) branch is not updated."
            exit 1
          
          fi

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"

      - name: Clean, complie & test code
        run: |
          chmod +x mvnw
          ./mvnw clean test --activate-profiles release,!dev
