name: Test Deploy

on:
  workflow_dispatch:

jobs:

  test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"

      - name: Show Settings
        run: |
          cat ~/.m2/settings.xml

      - name: Build
        continue-on-error: true
        run: |
          ls -als
          chmod +x mvnw
          ./mvnw clean deploy

